package com.epam.esm.gift_extended.genertors;

import java.util.List;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import com.epam.esm.gift_extended.entity.Tag;
import com.epam.esm.gift_extended.genertors.util.RandomUtil;

public class TagGenerator {

    private List<String> TagsPart = List.of(
            ("snorkeling " + "#underwater #adventure #naturephotography #2019 #reef #love "
                    + "#coral #instagood #followme #marinelife #beautiful #sealife "
                    + "#beach #bestoftheday #nightdive #nature #sea #tropic #ocean "
                    + "#photooftheday #scubadiving #tagblender #gopro #scuba #diving "
                    + "#fish #travel #dive #peacelovescuba").split(" #"));

    private Function<Integer, String> indexedTagNameSupplier = (i) -> {
        return RandomUtil.getRandomElementFromList(TagsPart) + " " + RandomUtil.getRandomElementFromList(TagsPart) + " "
                + RandomUtil.getRandomElementFromList(TagsPart) + " autoGeneratedTag " + i;
    };

    public List<Tag> generateTagList(int amount) {
        return IntStream.range(0, amount)
                .mapToObj(t -> (String) indexedTagNameSupplier.apply(t))
                .map(obj -> (String) obj)
                .map(str -> {
                    Tag tag = new Tag();
                    tag.setName(str);
                    return tag;
                })
                .collect(Collectors.toList());
    }

}
