package com.epam.esm.gift_extended.genertors;

import static com.epam.esm.gift_extended.entity.Role.*;

import java.util.List;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import com.epam.esm.gift_extended.entity.Role;
import com.epam.esm.gift_extended.entity.User;
import com.epam.esm.gift_extended.genertors.util.RandomUtil;

public class UserGenerator {

    private List<String> FirstNames = List.of("Borya", "Victor", "Artem", "Kirill", "Eughene", "Irena", "Nastya",
            "Liza");
    private List<String> LastNames = List.of("Borisov", "Victorvich", "Artemovich", "Kirillenko",
            "Eughenenko");

    private Function<Integer, String> indexedUsernameSupplier = i -> {
        return " "+RandomUtil.getRandomElementFromList(FirstNames) + " " + RandomUtil.getRandomElementFromList(LastNames)
                + " autoGeneratedUserName " + i;
    };

    public List<User> generateUserList(int amount) {
        return IntStream.range(0, amount)
                .mapToObj(t -> indexedUsernameSupplier.apply(t))
                .map(str -> str)
                .map(t -> {
                    User user = new User();
                    user.setName(t);
                    user.setPassword("123456");
                    user.setRole(USER);
                    return user;
                })
                .collect(Collectors.toList());
    }

}
