package com.epam.esm.gift_extended.genertors;

import static com.epam.esm.gift_extended.entity.Role.*;

import java.util.List;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import com.epam.esm.gift_extended.entity.Role;
import com.epam.esm.gift_extended.entity.User;
import com.epam.esm.gift_extended.genertors.util.RandomUtil;

public class UserGenerator {

    private List<String> FirstNames = List.of("Borya", "Victor", "Artem", "Kirill", "Eughene", "Irena", "Nastya",
            "Liza");
    private List<String> LastNames = List.of("Borisov", "Victorvich", "Artemovich", "Kirillenko",
            "Eughenenko");

    private Function<Integer, User> indexedUsernameSupplier = i -> {
        String username= " "+RandomUtil.getRandomElementFromList(FirstNames) + " " + RandomUtil.getRandomElementFromList(LastNames)
                + " autoGeneratedUserName " + i;
        User user=new User();
        user.setName(username);
        user.setPassword(i.toString());
        return user;
    };

    public List<User> generateUserList(int amount) {
        return IntStream.range(0, amount)
                .mapToObj(t -> indexedUsernameSupplier.apply(t))
                .peek(user -> user.setRole(USER))
                .collect(Collectors.toList());
    }

}
